/*
 * Enum_Command_Specifier_Codes.h
 *
 *  Created on: 9 okt. 2021
 *      Author: Daniel Mårtensson
 */

#ifndef CANOPEN_ENUMS_ENUM_COMMAND_SPECIFIER_CODES_H_
#define CANOPEN_ENUMS_ENUM_COMMAND_SPECIFIER_CODES_H_

enum {
	/* Network Management Services */
	COMMAND_SPECIFIER_NETWORK_MANAGMENT_SERVICE_START_REMOTE_NODE = 0x1,
	COMMAND_SPECIFIER_NETWORK_MANAGMENT_SERVICE_STOP_REMOTE_NODE = 0x2,
	COMMAND_SPECIFIER_NETWORK_MANAGMENT_SERVICE_ENTER_PRE_OPERATIONAL = 0x80,
	COMMAND_SPECIFIER_NETWORK_MANAGMENT_SERVICE_RESET_NODE = 0x81,
	COMMAND_SPECIFIER_NETWORK_MANAGMENT_SERVICE_RESET_COMMUNICATION = 0x82,

	/* LSS */
	COMMAND_SPECIFIER_SWITCH_MODE_GLOBAL_PROTOCOL = 0x4,
	COMMAND_SPECIFIER_SWITCH_MODE_SELECTIVE_PROTOCOL_VENDOR_ID = 0x40,
	COMMAND_SPECIFIER_SWITCH_MODE_SELECTIVE_PROTOCOL_PRODUCT_CODE = 0x41,
	COMMAND_SPECIFIER_SWITCH_MODE_SELECTIVE_PROTOCOL_REVISION_NUMBER = 0x42,
	COMMAND_SPECIFIER_SWITCH_MODE_SELECTIVE_PROTOCOL_SERIAL_NUMBER = 0x43,
	COMMAND_SPECIFIER_SWITCH_MODE_SELECTIVE_PROTOCOL_RESPONSE = 0x44,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_VENDOR_ID = 0x46,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_PRODUCT_CODE = 0x47,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_REVISION_NUMBER_LOW = 0x48,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_REVISION_NUMBER_HIGH = 0x49,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_SERIAL_NUMBER_LOW = 0x4A,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_SERIAL_NUMBER_HIGH = 0x4B,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_NON_CONFIGURED = 0x4C,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_CONFIGURED_RESPONSE = 0x4F,
	COMMAND_SPECIFIER_IDENTIFY_REMOTE_SLAVE_PROTOCOL_NON_CONFIGURED_RESPONSE = 0x50,
	COMMAND_SPECIFIER_CONFIGURE_NODE_ID = 0x11,
	COMMAND_SPECIFIER_CONFIGURE_BAUDRATE = 0x13,
	COMMAND_SPECIFIER_ACTIVATE_BAUDRATE = 0x15,
	COMMAND_SPECIFIER_STORE_CONFIGURATION = 0x17,
	COMMAND_SPECIFIER_INQUIRE_VENDOR_ID = 0x5A,
	COMMAND_SPECIFIER_INQUIRE_PRODUCT_CODE = 0x5B,
	COMMAND_SPECIFIER_INQUIRE_REVISION_NUMBER = 0x5C,
	COMMAND_SPECIFIER_INQUIRE_SERIAL_NUMBER = 0x5D,
	COMMAND_SPECIFIER_INQUIRE_NODE_ID = 0x5F,
};

#endif /* CANOPEN_ENUMS_ENUM_COMMAND_SPECIFIER_CODES_H_ */
