/*
 * Enum_Sub_Index_Value_Codes.h
 *
 *  Created on: 29 nov. 2025
 *      Author: Daniel Mårtensson
 */

#ifndef CANOPEN_GLOBAL_ENUMS_ENUM_SUB_INDEX_VALUE_CODES_H_
#define CANOPEN_GLOBAL_ENUMS_ENUM_SUB_INDEX_VALUE_CODES_H_

typedef enum{
    SUB_INDEX_VALUE_ERROR_BEHAVIOUR_OBJECT_NO_STOP        = 0x0,
    SUB_INDEX_VALUE_ERROR_BEHAVIOUR_OBJECT_PRE_OPERATION  = 0x1,
    SUB_INDEX_VALUE_ERROR_BEHAVIOUR_OBJECT_STOP_IMMEDIATE = 0x2,
}SUB_INDEX_VALUE_ERROR_BEHAVIOUR_OBJECT;

#endif /* CANOPEN_GLOBAL_ENUMS_ENUM_SUB_INDEX_VALUE_CODES_H_ */
