/*
 * Enum_Sub_Index_Codes.h
 *
 *  Created on: 29 nov. 2025
 *      Author: Daniel Mårtensson
 */

#ifndef CANOPEN_GLOBAL_ENUMS_ENUM_SUB_INDEX_CODES_H_
#define CANOPEN_GLOBAL_ENUMS_ENUM_SUB_INDEX_CODES_H_

typedef enum{
	SUB_INDEX_ERROR_BEHAVIOUR_OBJECT_COMMUNICATON_ERROR = 0x0,
	SUB_INDEX_ERROR_BEHAVIOUR_OBJECT_DEVICE_PROFILE_ERROR = 0x1,
	SUB_INDEX_ERROR_BEHAVIOUR_OBJECT_MANUFACTURE_SPECIFIC_ERROR = 0x2,
}SUB_INDEX_ERROR_BEHAVIOUR_OBJECT;

#endif /* CANOPEN_GLOBAL_ENUMS_ENUM_SUB_INDEX_CODES_H_ */
